Итоговое задание 5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -110,7 +110,7 @@ jobs:
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.9.0
         with:
-          ssh-private-key: ${{ secrets.SSH_KEY }}
+          ssh-private-key: django-insecure-#b7%9!4l5$49-^05xk8bjtuvew1&yphe7wl&9dwl8_gwdfe70+
       - name: Add server to known_hosts
         run: |
             ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
@@ -173,13 +173,14 @@ jobs:
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
             set -e
             cd habits
+            echo "Stopping containers..."
+            docker-compose down || { echo "docker-compose down failed"; exit 1; }
             
             echo "Pulling latest images..."
             docker-compose pull || { echo "docker-compose pull failed"; exit 1; }
 
             echo "Rebuilding and restarting containers..."
             docker-compose up -d --build || { echo "docker-compose up failed"; exit 1; }
-            
             
             echo "Docker Compose successfully restarted."
           EOF
