Итоговое задание 5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -111,51 +111,70 @@ jobs:
         uses: webfactory/ssh-agent@v0.9.0
         with:
           ssh-private-key: ${{ secrets.SSH_KEY }}
-      - name: Add server to known_hosts
-        run: |
-            ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
 
-      - name: Generate .env file
+      - name: Deploy to server
         run: |
-          echo "SSH_KEY: ${{ secrets.SSH_KEY }}" > .env
-          echo "DEBUG=False" >> .env
-          echo "SSH_USER: ${{ secrets.SSH_USER }}" >> .env
-          echo "SERVER_IP: ${{ secrets.SERVER_IP }}" >> .env
-          echo "SECRET_KEY: django-insecure-#b7%9!4l5$49-^05xk8bjtuvew1&yphe7wl&9dwl8_gwdfe70+" >> .env
-          echo "DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
-          echo "DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" >> .env
-          cat .env
-          
-      - name: Copy project files to server
-        run: |
-          rsync -avz --exclude '__pycache__' --exclude 'venv' --exclude '.git' . \
-            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits
+            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
+              ssh -l test -p22 51.250.41.177 << EOF2
+                docker-compose down
+                docker-compose pull
+                docker-compose push ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
+                docker-compose up -d --build
+#                docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
+#                docker stop habits || true
+#                docker rm habits || true
+#                docker run -d --name habits -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/habits:${{ github.sha }}
+              EOF2
+            EOF
 
-      - name: Upload .env to server
+      - name: Check running containers
         run: |
-          rsync -avz .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits/.env
-
-      - name: Install Docker and Docker Compose on server (if not installed)
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
-            set -e
-            if ! command -v docker &> /dev/null; then
-              echo "Docker not found. Installing..."
-              curl -fsSL https://get.docker.com | sudo sh
-              sudo usermod -aG docker $USER
-              newgrp docker
-            else
-              echo "Docker already installed."
-            fi
-  
-            if ! command -v docker-compose &> /dev/null; then
-              echo "Installing Docker Compose..."
-              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-              sudo chmod +x /usr/local/bin/docker-compose
-            else
-              echo "Docker Compose already installed."
-            fi
-          EOF
+          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker ps"
+#      - name: Add server to known_hosts
+#        run: |
+#            ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+#
+#      - name: Generate .env file
+#        run: |
+#          echo "SSH_KEY: ${{ secrets.SSH_KEY }}" > .env
+#          echo "DEBUG=False" >> .env
+#          echo "SSH_USER: ${{ secrets.SSH_USER }}" >> .env
+#          echo "SERVER_IP: ${{ secrets.SERVER_IP }}" >> .env
+#          echo "SECRET_KEY: django-insecure-#b7%9!4l5$49-^05xk8bjtuvew1&yphe7wl&9dwl8_gwdfe70+" >> .env
+#          echo "DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
+#          echo "DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" >> .env
+#          cat .env
+#
+#      - name: Copy project files to server
+#        run: |
+#          rsync -avz --exclude '__pycache__' --exclude 'venv' --exclude '.git' . \
+#            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits
+#
+#      - name: Upload .env to server
+#        run: |
+#          rsync -avz .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:habits/.env
+#
+#      - name: Install Docker and Docker Compose on server (if not installed)
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
+#            set -e
+#            if ! command -v docker &> /dev/null; then
+#              echo "Docker not found. Installing..."
+#              curl -fsSL https://get.docker.com | sudo sh
+#              sudo usermod -aG docker $USER
+#              newgrp docker
+#            else
+#              echo "Docker already installed."
+#            fi
+#
+#            if ! command -v docker-compose &> /dev/null; then
+#              echo "Installing Docker Compose..."
+#              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+#              sudo chmod +x /usr/local/bin/docker-compose
+#            else
+#              echo "Docker Compose already installed."
+#            fi
+#          EOF
 
 #      - name: Wait for backend container to be ready
 #        run: |
@@ -168,41 +187,40 @@ jobs:
 #            echo "Backend is ready."
 #          EOF
 
-      - name: Restart docker-compose on server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
-            set -e
-            cd habits
-            echo "Stopping containers..."
-            docker-compose run -e SECRET_KEY='django-insecure-#b7%9!4l5$49-^05xk8bjtuvew1&yphe7wl&9dwl8_gwdfe70+' web
-            docker-compose down || { echo "docker-compose down failed"; exit 1; }
-            
-            echo "Pulling latest images..."
-            docker-compose pull || { echo "docker-compose pull failed"; exit 1; }
+#      - name: Restart docker-compose on server
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
+#            set -e
+#            cd habits
+#            echo "Stopping containers..."
+#            docker-compose down || { echo "docker-compose down failed"; exit 1; }
+#
+#            echo "Pulling latest images..."
+#            docker-compose pull || { echo "docker-compose pull failed"; exit 1; }
+#
+#            echo "Rebuilding and restarting containers..."
+#            docker-compose up -d --build || { echo "docker-compose up failed"; exit 1; }
+#
+#            echo "Docker Compose successfully restarted."
+#          EOF
 
-            echo "Rebuilding and restarting containers..."
-            docker-compose up -d --build || { echo "docker-compose up failed"; exit 1; }
-            
-            echo "Docker Compose successfully restarted."
-          EOF
+#      - name: Run database migrations
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
+#            set -e
+#            cd habits
+#            echo "Running database migrations..."
+#            docker-compose exec backend python manage.py migrate || { echo "Migrations failed"; exit 1; }
+#          EOF
 
-      - name: Run database migrations
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
-            set -e
-            cd habits
-            echo "Running database migrations..."
-            docker-compose exec backend python manage.py migrate || { echo "Migrations failed"; exit 1; }
-          EOF
+#      - name: Show Postgres logs if failed
+#        if: failure()
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker logs postgres_data || true"
 
-      - name: Show Postgres logs if failed
-        if: failure()
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker logs postgres_data || true"
-
-      - name: Check running containers
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker ps"
+#      - name: Check running containers
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker ps"
 
 
 #      - name: Deploy to Server
